[project]
name = "slobs-cli"
version = "0.3.0"
description = "A command line application for Streamlabs Desktop"
authors = [{ name = "onyx-and-iris", email = "code@onyxandiris.online" }]
dependencies = ["pyslobs>=2.0.4", "asyncclick>=8.1.8"]
requires-python = ">=3.12"
readme = "README.md"
license = { text = "MIT" }

[project.scripts]
slobs-cli = "slobs_cli.cli:run"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true

[tool.pdm.scripts]
cli.cmd = "slobs-cli {args}"
cli.env_file = ".env"
